# Generated by Django 2.0.6 on 2018-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20180807_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=255)),
                ('conference_id', models.TextField(max_length=255)),
            ],
        ),
    ]
