# Generated by Django 2.0.6 on 2018-09-25 06:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_userconference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
